- hosts: digitalocean

  vars_files:
    - vars.yml

  tasks:
    - name: Delete droplet
      digital_ocean: >
        state=absent
        name={{ do_name }}
        unique_name=yes
        api_token={{ do_api_token }}